version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
 postgresql:
    image: postgres:9.4
    expose:
      - "5432"
    volumes:
      - 'data/tmp'
    environment:
      POSTGRES_USER: 'example'
      POSTGRES_PASSWORD: 'sesame'
      POSTGRES_DB: 'example'
